// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SistemaParqueadero.API.Data;

#nullable disable

namespace SistemaParqueadero.API.Migrations
{
    [DbContext(typeof(ParqueaderoDbContext))]
    [Migration("20260222175150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("parqueadero")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SistemaParqueadero.Models.RegistroParqueo", b =>
                {
                    b.Property<int>("RegistroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegistroId"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("HorasCalculadas")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("MontoCobrado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ObservacionesIngreso")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ObservacionesSalida")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoTarifa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("UsuarioIngresoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioSalidaId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("RegistroId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaHoraIngreso");

                    b.HasIndex("FechaHoraSalida");

                    b.HasIndex("UsuarioIngresoId");

                    b.HasIndex("UsuarioSalidaId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("RegistrosParqueo", "parqueadero");
                });

            modelBuilder.Entity("SistemaParqueadero.Models.Usuario1", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Usuarios1", "parqueadero");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 2, 22, 17, 51, 49, 385, DateTimeKind.Utc).AddTicks(4291),
                            NombreCompleto = "Administrador del Sistema",
                            PasswordHash = "$2a$11$e3hgNTXLILMztMdzduJYxOWtifeFGS3b3P9DM4K0ZD/sxpYzgwfWW",
                            Rol = "Administrador",
                            Username = "admin"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Activo = true,
                            FechaCreacion = new DateTime(2026, 2, 22, 17, 51, 49, 505, DateTimeKind.Utc).AddTicks(5650),
                            NombreCompleto = "Operador Principal",
                            PasswordHash = "$2a$11$r2YPU32.gwJc0k9Zw8LuOOwr9IVhuWJODQegirX922/yDkcnj4EvW",
                            Rol = "Operador",
                            Username = "operador"
                        });
                });

            modelBuilder.Entity("SistemaParqueadero.Models.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehiculoId"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Marca")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("VehiculoId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Vehiculos", "parqueadero");
                });

            modelBuilder.Entity("SistemaParqueadero.Models.RegistroParqueo", b =>
                {
                    b.HasOne("SistemaParqueadero.Models.Usuario1", "UsuarioIngreso")
                        .WithMany("RegistrosIngreso")
                        .HasForeignKey("UsuarioIngresoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaParqueadero.Models.Usuario1", "UsuarioSalida")
                        .WithMany("RegistrosSalida")
                        .HasForeignKey("UsuarioSalidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaParqueadero.Models.Vehiculo", "Vehiculo")
                        .WithMany("Registros")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioIngreso");

                    b.Navigation("UsuarioSalida");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("SistemaParqueadero.Models.Usuario1", b =>
                {
                    b.Navigation("RegistrosIngreso");

                    b.Navigation("RegistrosSalida");
                });

            modelBuilder.Entity("SistemaParqueadero.Models.Vehiculo", b =>
                {
                    b.Navigation("Registros");
                });
#pragma warning restore 612, 618
        }
    }
}
